const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const { test, after } = require('node:test')

const volumePath = fs.mkdtempSync(path.join(os.tmpdir(), 'minthunter-db-sync-'))
process.env.RAILWAY_VOLUME_MOUNT_PATH = volumePath

const db = require('../src/db')
const generator = path.join(__dirname, '..', 'scripts', 'generate-codes.js')

after(() => fs.rmSync(volumePath, { recursive: true, force: true }))

test('refreshes a console-created access-code batch before saving bot writes', async () => {
  await db.initDb()
  db.prepare('INSERT INTO users (telegram_id, username) VALUES (?, ?)').run(1, 'first-user')

  const output = execFileSync(process.execPath, [generator, '1', '30'], {
    encoding: 'utf8',
    env: { ...process.env, RAILWAY_VOLUME_MOUNT_PATH: volumePath },
  })
  const generatedCode = output.split('\n').find((line) => /^MH-[A-F0-9]{6}$/.test(line))
  assert.match(generatedCode, /^MH-[A-F0-9]{6}$/)

  // This write makes the running process persist its in-memory state. The code
  // generated by the separate process must survive that save.
  db.prepare('INSERT INTO users (telegram_id, username) VALUES (?, ?)').run(2, 'second-user')

  const accessCode = db.prepare('SELECT code, used_by FROM access_codes WHERE code = ?').get(generatedCode)
  assert.equal(accessCode.code, generatedCode)
  assert.equal(accessCode.used_by, null)
})

test('returns a real lastInsertRowid for mint jobs before persistence', () => {
  const inserted = db.prepare(
    'INSERT INTO mint_jobs (telegram_id, wallet_id, contract_address, mint_function, mint_price, mint_mode, gas_limit, status, chain) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'
  ).run(99, 1, '0x1111111111111111111111111111111111111111', null, '0', 'normal', 250000, 'pending', 'ethereum')
  assert.ok(inserted.lastInsertRowid > 0)
  const job = db.prepare('SELECT id FROM mint_jobs WHERE id = ?').get(inserted.lastInsertRowid)
  assert.equal(job.id, inserted.lastInsertRowid)
})

test('reports update changes before persistence and restores interrupted access-code claims', () => {
  const claimUserId = 3
  db.prepare('INSERT INTO users (telegram_id, username, is_authorized) VALUES (?, ?, 0)').run(claimUserId, 'claim-user')
  db.prepare('INSERT INTO access_codes (code, used_by, used_at, expires_at) VALUES (?, ?, datetime(\'now\'), datetime(\'now\', \'+30 days\'))')
    .run('MH-ABC123', claimUserId)

  const claimed = db.prepare('UPDATE access_codes SET used_at = datetime(\'now\') WHERE code = ? AND used_by IS NOT NULL')
    .run('MH-ABC123')
  assert.equal(claimed.changes, 1)

  const recovered = db.reconcileInterruptedAccessCodeClaims()
  assert.equal(recovered, 1)

  const user = db.prepare('SELECT is_authorized, access_expires FROM users WHERE telegram_id = ?').get(claimUserId)
  assert.equal(user.is_authorized, 1)
  assert.ok(new Date(user.access_expires) > new Date())
})
