const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const test = require('node:test')

const volumePath = fs.mkdtempSync(path.join(os.tmpdir(), 'minthunter-db-sync-'))
process.env.RAILWAY_VOLUME_MOUNT_PATH = volumePath

const db = require('../src/db')
const generator = path.join(__dirname, '..', 'scripts', 'generate-codes.js')

test('refreshes a console-created access-code batch before saving bot writes', async (t) => {
  t.after(() => fs.rmSync(volumePath, { recursive: true, force: true }))

  await db.initDb()
  db.prepare('INSERT INTO users (telegram_id, username) VALUES (?, ?)').run(1, 'first-user')

  const output = execFileSync(process.execPath, [generator, '1', '30'], {
    encoding: 'utf8',
    env: { ...process.env, RAILWAY_VOLUME_MOUNT_PATH: volumePath },
  })
  const generatedCode = output.split('\n').find((line) => /^MH-[A-F0-9]{6}$/.test(line))
  assert.match(generatedCode, /^MH-[A-F0-9]{6}$/)

  // This write makes the running process persist its in-memory state. The code
  // generated by the separate process must survive that save.
  db.prepare('INSERT INTO users (telegram_id, username) VALUES (?, ?)').run(2, 'second-user')

  const accessCode = db.prepare('SELECT code, used_by FROM access_codes WHERE code = ?').get(generatedCode)
  assert.equal(accessCode.code, generatedCode)
  assert.equal(accessCode.used_by, null)
})
